version: "3.0"
services:
  spark-master:
    container_name: spark-master
    image: docker.io/bitnami/spark:latest
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    volumes:
      - ./data:/opt/bitnami/spark/data
      - ./src:/opt/bitnami/spark/app
    ports:
      - "8090:8080"
      - "7077:7077"
      - "8888:8888"

  spark-worker-a:
    image: docker.io/bitnami/spark:latest
    ports:
      - "8091:8080"
      - "7000:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G

  spark-worker-b:
    image: docker.io/bitnami/spark:latest
    ports:
      - "8092:8080"
      - "7001:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G

    volumes:
      - ./data:/opt/bitnami/spark/data
      - ./src:/opt/bitnami/spark/app